hi
hi
1
Internal Server Error: /admin/api/dimension/add/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 1804, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 926, in log_addition
    object_repr=str(obj),
                ^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\models.py", line 42, in __str__
    return self.size[:50]
           ^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'size'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'order_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 133, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `order_number` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Dimension` instance.
Original exception text was: 'Dimension' object has no attribute 'order_number'.
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'order_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 133, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `order_number` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Dimension` instance.
Original exception text was: 'Dimension' object has no attribute 'order_number'.
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'order_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 133, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `order_number` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Dimension` instance.
Original exception text was: 'Dimension' object has no attribute 'order_number'.
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'order_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 133, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `order_number` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Dimension` instance.
Original exception text was: 'Dimension' object has no attribute 'order_number'.
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 138, in post
    max_index_position = Dimension.objects.aggregate(Max('index_position'))['index_position__max'] or 0
                                                     ^^^
NameError: name 'Max' is not defined
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 138, in post
    max_index_position = Dimension.objects.aggregate(Max('index_position'))['index_position__max'] or 0
                                                     ^^^
NameError: name 'Max' is not defined
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 134, in get
    dimensions = Dimension.objects.all().order_by('index_position')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1659, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 2221, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'index_position' into field. Choices are: height, id, length, width
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 134, in get
    dimensions = Dimension.objects.all().order_by('index_position')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1659, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 2221, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'index_position' into field. Choices are: height, id, length, width
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 41, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 41, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 41, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 41, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 41, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 41, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 41, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 41, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 35, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 35, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 35, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 35, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /open-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 35, in get
    page = self.paginate_queryset(open_orders)
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenOrdersListView' object has no attribute 'paginate_queryset'
Internal Server Error: /all-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: row value misused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\pagination.py", line 216, in paginate_queryset
    return list(self.page)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\paginator.py", line 174, in __len__
    return len(self.object_list)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: row value misused
Internal Server Error: /all-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: row value misused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\pagination.py", line 216, in paginate_queryset
    return list(self.page)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\paginator.py", line 174, in __len__
    return len(self.object_list)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: row value misused
Internal Server Error: /all-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 112, in get_queryset
    queryset = queryset.annotate(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1133, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 278, in resolve_expression
    [
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 279, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1451, in resolve_expression
    c.cases[pos] = case.resolve_expression(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1377, in resolve_expression
    c.result = c.result.resolve_expression(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1976, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1823, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_date' into field. Choices are: backorder, backorder_number, created, customer_name, delay_date, delay_tbd, id, is_oldest_order, item_subtype_dict, item_type_dict, minimized_status, notes_array, order_number, packages_array, quote, ready, ship_date, shipped, updated
Internal Server Error: /all-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 112, in get_queryset
    queryset = queryset.annotate(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1133, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 278, in resolve_expression
    [
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 279, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1451, in resolve_expression
    c.cases[pos] = case.resolve_expression(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1377, in resolve_expression
    c.result = c.result.resolve_expression(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1976, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1823, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_date' into field. Choices are: backorder, backorder_number, created, customer_name, delay_date, delay_tbd, id, is_oldest_order, item_subtype_dict, item_type_dict, minimized_status, notes_array, order_number, packages_array, quote, ready, ship_date, shipped, updated
Internal Server Error: /all-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 112, in get_queryset
    queryset = queryset.annotate(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1133, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 278, in resolve_expression
    [
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 279, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1451, in resolve_expression
    c.cases[pos] = case.resolve_expression(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1377, in resolve_expression
    c.result = c.result.resolve_expression(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1976, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1823, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_date' into field. Choices are: backorder, backorder_number, created, customer_name, delay_date, delay_tbd, id, is_oldest_order, item_subtype_dict, item_type_dict, minimized_status, notes_array, order_number, packages_array, quote, ready, ship_date, shipped, updated
Internal Server Error: /all-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 112, in get_queryset
    queryset = queryset.annotate(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1133, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 278, in resolve_expression
    [
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 279, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1451, in resolve_expression
    c.cases[pos] = case.resolve_expression(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1377, in resolve_expression
    c.result = c.result.resolve_expression(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1976, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1823, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_date' into field. Choices are: backorder, backorder_number, created, customer_name, delay_date, delay_tbd, id, is_oldest_order, item_subtype_dict, item_type_dict, minimized_status, notes_array, order_number, packages_array, quote, ready, ship_date, shipped, updated
Internal Server Error: /all-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 112, in get_queryset
    queryset = queryset.annotate(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1133, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 278, in resolve_expression
    [
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 279, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1451, in resolve_expression
    c.cases[pos] = case.resolve_expression(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1377, in resolve_expression
    c.result = c.result.resolve_expression(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1976, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1823, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_date' into field. Choices are: backorder, backorder_number, created, customer_name, delay_date, delay_tbd, id, is_oldest_order, item_subtype_dict, item_type_dict, minimized_status, notes_array, order_number, packages_array, quote, ready, ship_date, shipped, updated
Internal Server Error: /all-orders/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 112, in get_queryset
    queryset = queryset.annotate(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1133, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 278, in resolve_expression
    [
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 279, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1451, in resolve_expression
    c.cases[pos] = case.resolve_expression(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 1377, in resolve_expression
    c.result = c.result.resolve_expression(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1976, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1823, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_date' into field. Choices are: backorder, backorder_number, created, customer_name, delay_date, delay_tbd, id, is_oldest_order, item_subtype_dict, item_type_dict, minimized_status, notes_array, order_number, packages_array, quote, ready, ship_date, shipped, updated
