hi
hi
1
Internal Server Error: /admin/api/dimension/add/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 1804, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\contrib\admin\options.py", line 926, in log_addition
    object_repr=str(obj),
                ^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\models.py", line 42, in __str__
    return self.size[:50]
           ^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'size'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'order_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 133, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `order_number` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Dimension` instance.
Original exception text was: 'Dimension' object has no attribute 'order_number'.
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'order_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 133, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `order_number` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Dimension` instance.
Original exception text was: 'Dimension' object has no attribute 'order_number'.
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'order_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 133, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `order_number` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Dimension` instance.
Original exception text was: 'Dimension' object has no attribute 'order_number'.
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dimension' object has no attribute 'order_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 133, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `order_number` on serializer `OrderSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Dimension` instance.
Original exception text was: 'Dimension' object has no attribute 'order_number'.
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 138, in post
    max_index_position = Dimension.objects.aggregate(Max('index_position'))['index_position__max'] or 0
                                                     ^^^
NameError: name 'Max' is not defined
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 138, in post
    max_index_position = Dimension.objects.aggregate(Max('index_position'))['index_position__max'] or 0
                                                     ^^^
NameError: name 'Max' is not defined
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 134, in get
    dimensions = Dimension.objects.all().order_by('index_position')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1659, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 2221, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'index_position' into field. Choices are: height, id, length, width
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 134, in get
    dimensions = Dimension.objects.all().order_by('index_position')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1659, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 2221, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'index_position' into field. Choices are: height, id, length, width
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
Internal Server Error: /dimensions/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 136, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
           ^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\fields.py", line 915, in to_representation
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10"'
