Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QBworkbook.xlsx
FILE Name: QBworkbook.xlsx
Entering OrderReportUploadView
Entering OrderReportUploadView
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QBworkbook.xlsx
FILE Name: QBworkbook.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QBworkbook.xlsx
FILE Name: QBworkbook.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_older.xlsx
FILE Name: QB_workbook_older.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_older.xlsx
FILE Name: QB_workbook_older.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\QB_workbook_newer.xlsx
FILE Name: QB_workbook_newer.xlsx
Internal Server Error: /reports/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\scripts\check_order_report.py", line 72, in check_if_correct_workbook
    sort_workbook(sheet)
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\scripts\check_order_report.py", line 148, in sort_workbook
    update_orders_dict(new_order)
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\scripts\check_order_report.py", line 47, in update_orders_dict
    existing_order.save()
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 124, in post
    order_report.save()
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\models.py", line 31, in save
    if OrderReport.objects.count() >= 10:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 83, in _execute
    self.db.validate_no_broken_transaction()
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\base\base.py", line 531, in validate_no_broken_transaction
    raise TransactionManagementError(
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
Internal Server Error: /reports/
Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\scripts\check_order_report.py", line 72, in check_if_correct_workbook
    sort_workbook(sheet)
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\scripts\check_order_report.py", line 148, in sort_workbook
    update_orders_dict(new_order)
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\scripts\check_order_report.py", line 47, in update_orders_dict
    existing_order.save()
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\base.py", line 1054, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\views.py", line 124, in post
    order_report.save()
  File "C:\Users\Michelle\Documents\Coding_Projects\Production-Project\api\models.py", line 31, in save
    if OrderReport.objects.count() >= 10:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\utils.py", line 83, in _execute
    self.db.validate_no_broken_transaction()
  File "C:\Users\Michelle\.virtualenvs\Production-Project-ch8sWzvY\Lib\site-packages\django\db\backends\base\base.py", line 531, in validate_no_broken_transaction
    raise TransactionManagementError(
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
Entering OrderReportUploadView
Entering POST request
FILE PATH: C:\Users\Michelle\Documents\Coding_Projects\Production-Project\media\20231008 order report.xlsx
FILE Name: 20231008 order report.xlsx
Entering OrderReportUploadView
